name: Generate Plots

on:
  push:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        echo "upgrading pip"
        python -m pip install --upgrade pip
        echo "Installing the following packages"
        cat requirements.txt
        pip install -r requirements.txt

    - name: Generate plots
      run: |
        python generate_plots.py